/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WiringRouteImport } from './routes/wiring'
import { Route as BenchJobIdRouteImport } from './routes/bench.$jobId'
import { Route as WiringIndexRouteImport } from './routes/wiring.index'
import { Route as WiringModelIdRouteImport } from './routes/wiring.$modelId'
import { Route as PrintDiagramModelIdRouteImport } from './routes/print.diagram.$modelId'
import { Route as PrintReportJobIdRouteImport } from './routes/print.report.$jobId'
import { Route as PrintWiringSheetIdRouteImport } from './routes/print.wiring.$sheetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WiringRoute = WiringRouteImport.update({
  id: '/wiring',
  path: '/wiring',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchJobIdRoute = BenchJobIdRouteImport.update({
  id: '/bench/$jobId',
  path: '/bench/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const WiringIndexRoute = WiringIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WiringRoute,
} as any)
const WiringModelIdRoute = WiringModelIdRouteImport.update({
  id: '/$modelId',
  path: '/$modelId',
  getParentRoute: () => WiringRoute,
} as any)
const PrintDiagramModelIdRoute = PrintDiagramModelIdRouteImport.update({
  id: '/print/diagram/$modelId',
  path: '/print/diagram/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintReportJobIdRoute = PrintReportJobIdRouteImport.update({
  id: '/print/report/$jobId',
  path: '/print/report/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintWiringSheetIdRoute = PrintWiringSheetIdRouteImport.update({
  id: '/print/wiring/$sheetId',
  path: '/print/wiring/$sheetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wiring': typeof WiringRouteWithChildren
  '/bench/$jobId': typeof BenchJobIdRoute
  '/wiring/$modelId': typeof WiringModelIdRoute
  '/wiring/': typeof WiringIndexRoute
  '/print/diagram/$modelId': typeof PrintDiagramModelIdRoute
  '/print/report/$jobId': typeof PrintReportJobIdRoute
  '/print/wiring/$sheetId': typeof PrintWiringSheetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bench/$jobId': typeof BenchJobIdRoute
  '/wiring/$modelId': typeof WiringModelIdRoute
  '/wiring': typeof WiringIndexRoute
  '/print/diagram/$modelId': typeof PrintDiagramModelIdRoute
  '/print/report/$jobId': typeof PrintReportJobIdRoute
  '/print/wiring/$sheetId': typeof PrintWiringSheetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wiring': typeof WiringRouteWithChildren
  '/bench/$jobId': typeof BenchJobIdRoute
  '/wiring/$modelId': typeof WiringModelIdRoute
  '/wiring/': typeof WiringIndexRoute
  '/print/diagram/$modelId': typeof PrintDiagramModelIdRoute
  '/print/report/$jobId': typeof PrintReportJobIdRoute
  '/print/wiring/$sheetId': typeof PrintWiringSheetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/wiring'
    | '/bench/$jobId'
    | '/wiring/$modelId'
    | '/wiring/'
    | '/print/diagram/$modelId'
    | '/print/report/$jobId'
    | '/print/wiring/$sheetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bench/$jobId'
    | '/wiring/$modelId'
    | '/wiring'
    | '/print/diagram/$modelId'
    | '/print/report/$jobId'
    | '/print/wiring/$sheetId'
  id:
    | '__root__'
    | '/'
    | '/wiring'
    | '/bench/$jobId'
    | '/wiring/$modelId'
    | '/wiring/'
    | '/print/diagram/$modelId'
    | '/print/report/$jobId'
    | '/print/wiring/$sheetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WiringRoute: typeof WiringRouteWithChildren
  BenchJobIdRoute: typeof BenchJobIdRoute
  PrintDiagramModelIdRoute: typeof PrintDiagramModelIdRoute
  PrintReportJobIdRoute: typeof PrintReportJobIdRoute
  PrintWiringSheetIdRoute: typeof PrintWiringSheetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiring': {
      id: '/wiring'
      path: '/wiring'
      fullPath: '/wiring'
      preLoaderRoute: typeof WiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench/$jobId': {
      id: '/bench/$jobId'
      path: '/bench/$jobId'
      fullPath: '/bench/$jobId'
      preLoaderRoute: typeof BenchJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiring/': {
      id: '/wiring/'
      path: '/'
      fullPath: '/wiring/'
      preLoaderRoute: typeof WiringIndexRouteImport
      parentRoute: typeof WiringRoute
    }
    '/wiring/$modelId': {
      id: '/wiring/$modelId'
      path: '/$modelId'
      fullPath: '/wiring/$modelId'
      preLoaderRoute: typeof WiringModelIdRouteImport
      parentRoute: typeof WiringRoute
    }
    '/print/diagram/$modelId': {
      id: '/print/diagram/$modelId'
      path: '/print/diagram/$modelId'
      fullPath: '/print/diagram/$modelId'
      preLoaderRoute: typeof PrintDiagramModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/report/$jobId': {
      id: '/print/report/$jobId'
      path: '/print/report/$jobId'
      fullPath: '/print/report/$jobId'
      preLoaderRoute: typeof PrintReportJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/wiring/$sheetId': {
      id: '/print/wiring/$sheetId'
      path: '/print/wiring/$sheetId'
      fullPath: '/print/wiring/$sheetId'
      preLoaderRoute: typeof PrintWiringSheetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WiringRouteChildren {
  WiringModelIdRoute: typeof WiringModelIdRoute
  WiringIndexRoute: typeof WiringIndexRoute
}

const WiringRouteChildren: WiringRouteChildren = {
  WiringModelIdRoute: WiringModelIdRoute,
  WiringIndexRoute: WiringIndexRoute,
}

const WiringRouteWithChildren =
  WiringRoute._addFileChildren(WiringRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WiringRoute: WiringRouteWithChildren,
  BenchJobIdRoute: BenchJobIdRoute,
  PrintDiagramModelIdRoute: PrintDiagramModelIdRoute,
  PrintReportJobIdRoute: PrintReportJobIdRoute,
  PrintWiringSheetIdRoute: PrintWiringSheetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
